### ISSUE TITLE
Jackson NoSuchMethodError

### ISSUE THREAD

**Issue by timterry** [dparis/lein-essthree#1]
Hi,

I'm having some trouble getting the lein essthree plugin to work. Basically i did a 'lein new uberjar-test' then modified the project.clj as below. Then when running lein essthree i get a jackson no such method error (stack trace below). The jackson dependency (2.5.3) includes the method it can't find so perhaps i've misunderstood the config. Any ideas?

Thanks

```
(defproject uberjar-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :plugins [[lein-essthree "0.2.1"]]
  :uberjar-name "uberjartest.jar"
  :essthree  {:deploy {:type          :uberjar
                       :bucket        "test.com"
                       :path          "test/"
                       :aws-creds     {:access-key-id     "test"
                                       :secret-access-key "test"}}})
```

```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:472)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:391)
        at com.amazonaws.util.json.Jackson.<clinit>(Jackson.java:32)
        at com.amazonaws.internal.config.InternalConfig.loadfrom(InternalConfig.java:233)
        at com.amazonaws.internal.config.InternalConfig.load(InternalConfig.java:251)
        at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:308)
        at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:139)
        at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:134)
        at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:95)
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:42)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:259)
        at amazonica.core$eval4478$loading__4910__auto____4479.invoke(core.clj:1)
        at amazonica.core$eval4478.invoke(core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6619)
        at clojure.lang.Compiler.eval(Compiler.java:6608)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5018.invoke(core.clj:5530)
        at clojure.core$load.doInvoke(core.clj:5529)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5336)
        at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
        at clojure.core$load_lib.doInvoke(core.clj:5374)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:619)
        at clojure.core$load_libs.doInvoke(core.clj:5413)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:621)
        at clojure.core$use.doInvoke(core.clj:5507)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at amazonica.aws.s3$eval4472$loading__4910__auto____4473.invoke(s3.clj:1)
        at amazonica.aws.s3$eval4472.invoke(s3.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6619)
        at clojure.lang.Compiler.eval(Compiler.java:6608)
        at clojure.lang.Compiler.load(Compiler.java:7064)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5018.invoke(core.clj:5530)
        at clojure.core$load.doInvoke(core.clj:5529)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5336)
        at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
        at clojure.core$load_lib.doInvoke(core.clj:5374)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:619)
        at clojure.core$load_libs.doInvoke(core.clj:5413)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:619)
        at clojure.core$require.doInvoke(core.clj:5496)
        at clojure.lang.RestFn.invoke(RestFn.java:551)
        at lein_essthree.s3$eval4466$loading__4910__auto____4467.invoke(s3.clj:1)
        at lein_essthree.s3$eval4466.invoke(s3.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6619)
```

**Comment by timterry** [comment]
I found that the cause was an older version of lein. Updated to 2.5.3 and worked with no issues.
